/*=============================================================
  LOGFACIL ERP v3.0 - Script de Migração
  Executar sobre banco existente v2.0
  Banco: Firebird 3.0
=============================================================*/

/* ══════════════════════════════════════════════════════════
   NOVAS SEQUENCES
   ══════════════════════════════════════════════════════════ */
CREATE SEQUENCE SEQ_ORCAMENTOS;
CREATE SEQUENCE SEQ_ORC_ITENS;
CREATE SEQUENCE SEQ_NF_SAIDA;
CREATE SEQUENCE SEQ_NF_SAIDA_ITENS;
CREATE SEQUENCE SEQ_CONTAS_PAGAR;
CREATE SEQUENCE SEQ_CONTAS_RECEBER;
CREATE SEQUENCE SEQ_PAGAMENTOS;
CREATE SEQUENCE SEQ_RECEBIMENTOS;
CREATE SEQUENCE SEQ_FORMAS_PGTO;
CREATE SEQUENCE SEQ_CAIXAS;
CREATE SEQUENCE SEQ_CAIXA_MOV;

/* ══════════════════════════════════════════════════════════
   CAMPOS FISCAIS EM PRODUTOS (ALTER TABLE)
   ══════════════════════════════════════════════════════════ */
ALTER TABLE PRODUTOS ADD ORIGEM         CHAR(1)     DEFAULT '0';
ALTER TABLE PRODUTOS ADD CST_ICMS       VARCHAR(4);
ALTER TABLE PRODUTOS ADD CSOSN          VARCHAR(4);
ALTER TABLE PRODUTOS ADD ALIQ_ICMS      NUMERIC(7,2);
ALTER TABLE PRODUTOS ADD BASE_ICMS      NUMERIC(7,2)  DEFAULT 100;
ALTER TABLE PRODUTOS ADD CST_PIS        VARCHAR(3);
ALTER TABLE PRODUTOS ADD ALIQ_PIS       NUMERIC(7,4);
ALTER TABLE PRODUTOS ADD CST_COFINS     VARCHAR(3);
ALTER TABLE PRODUTOS ADD ALIQ_COFINS    NUMERIC(7,4);
ALTER TABLE PRODUTOS ADD CST_IPI        VARCHAR(3);
ALTER TABLE PRODUTOS ADD ALIQ_IPI       NUMERIC(7,2);
ALTER TABLE PRODUTOS ADD PESO_BRUTO     NUMERIC(10,3);
ALTER TABLE PRODUTOS ADD PESO_LIQUIDO   NUMERIC(10,3);

/* ══════════════════════════════════════════════════════════
   CAMPOS FISCAIS EM CLIENTES (ALTER TABLE)
   ══════════════════════════════════════════════════════════ */
ALTER TABLE CLIENTES ADD INDIC_IE       CHAR(1) DEFAULT '9';  /* 1=Contribuinte 2=Isento 9=NaoContribuinte */
ALTER TABLE CLIENTES ADD COD_MUNICIPIO  VARCHAR(8);
ALTER TABLE CLIENTES ADD SUFRAMA        VARCHAR(9);

/* ══════════════════════════════════════════════════════════
   CAMPOS FISCAIS EM FORNECEDORES (ALTER TABLE)
   ══════════════════════════════════════════════════════════ */
ALTER TABLE FORNECEDORES ADD INDIC_IE      CHAR(1) DEFAULT '1';
ALTER TABLE FORNECEDORES ADD COD_MUNICIPIO VARCHAR(8);
ALTER TABLE FORNECEDORES ADD SUFRAMA       VARCHAR(9);

/* ══════════════════════════════════════════════════════════
   TABELA DE FORMAS DE PAGAMENTO
   ══════════════════════════════════════════════════════════ */
CREATE TABLE FORMAS_PGTO (
  ID          DM_ID,
  DESCRICAO   DM_NOME,
  TIPO        VARCHAR(20) NOT NULL
    CHECK (TIPO IN ('DINHEIRO','CHEQUE','CARTAO_DEBITO','CARTAO_CREDITO',
                    'PIX','BOLETO','TRANSFERENCIA','OUTROS')),
  PRAZO_DIAS  INTEGER DEFAULT 0,
  ATIVO       DM_ATIVO,
  CONSTRAINT PK_FORMAS_PGTO PRIMARY KEY (ID)
);

CREATE TRIGGER TBI_FORMAS_PGTO FOR FORMAS_PGTO ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_FORMAS_PGTO; END;

/* ══════════════════════════════════════════════════════════
   TABELA DE ORÇAMENTOS DE VENDA
   ══════════════════════════════════════════════════════════ */
CREATE TABLE ORCAMENTOS (
  ID             DM_ID,
  NUMERO         INTEGER NOT NULL,
  ID_CLIENTE     INTEGER NOT NULL,
  ID_USUARIO     INTEGER NOT NULL,
  DT_EMISSAO     DM_DATA DEFAULT CURRENT_DATE,
  DT_VALIDADE    DM_DATA,
  STATUS         VARCHAR(20) DEFAULT 'ABERTO'
    CHECK (STATUS IN ('ABERTO','CONVERTIDO','EXPIRADO','CANCELADO')),
  ID_VENDA       INTEGER,        /* preenchido quando convertido */
  VL_PRODUTOS    DM_VALOR,
  VL_FRETE       DM_VALOR,
  VL_DESCONTO    DM_VALOR,
  VL_TOTAL       DM_VALOR,
  COND_PAGTO     VARCHAR(60),
  OBS            VARCHAR(500),
  DT_CADASTRO    DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ORCAMENTOS     PRIMARY KEY (ID),
  CONSTRAINT UQ_ORC_NUMERO     UNIQUE (NUMERO),
  CONSTRAINT FK_ORC_CLIENTE    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
  CONSTRAINT FK_ORC_USUARIO    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_ORC_VENDA      FOREIGN KEY (ID_VENDA)   REFERENCES VENDAS(ID)
);

CREATE TABLE ORCAMENTOS_ITENS (
  ID          DM_ID,
  ID_ORCAMENTO INTEGER NOT NULL,
  ITEM        SMALLINT NOT NULL,
  ID_PRODUTO  INTEGER NOT NULL,
  QUANTIDADE  DM_QTD  NOT NULL,
  VL_UNITARIO DM_VALOR NOT NULL,
  VL_DESCONTO DM_VALOR,
  VL_TOTAL    DM_VALOR NOT NULL,
  CONSTRAINT PK_ORC_ITENS  PRIMARY KEY (ID),
  CONSTRAINT FK_OI_ORC     FOREIGN KEY (ID_ORCAMENTO) REFERENCES ORCAMENTOS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_OI_PROD    FOREIGN KEY (ID_PRODUTO)   REFERENCES PRODUTOS(ID)
);

SET TERM ^ ;
CREATE TRIGGER TBI_ORCAMENTOS FOR ORCAMENTOS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_ORCAMENTOS;
  IF (NEW.NUMERO IS NULL OR NEW.NUMERO = 0) THEN NEW.NUMERO = NEW.ID;
END^
CREATE TRIGGER TBI_ORC_ITENS FOR ORCAMENTOS_ITENS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_ORC_ITENS; END^
SET TERM ; ^

/* ══════════════════════════════════════════════════════════
   NOTA FISCAL DE SAÍDA (emissão própria)
   ══════════════════════════════════════════════════════════ */
CREATE TABLE NF_SAIDA (
  ID               DM_ID,
  NUMERO           INTEGER NOT NULL,
  SERIE            VARCHAR(3) DEFAULT '1',
  ID_CLIENTE       INTEGER NOT NULL,
  ID_VENDA         INTEGER,
  ID_USUARIO       INTEGER NOT NULL,
  DT_EMISSAO       DM_HORA DEFAULT CURRENT_TIMESTAMP,
  DT_SAIDA         DM_HORA,
  NATUREZA_OP      VARCHAR(60) DEFAULT 'VENDA DE MERCADORIA',
  TIPO_NF          CHAR(1) DEFAULT '1' CHECK (TIPO_NF IN ('0','1')), /* 0=Entrada 1=Saída */
  FINALIDADE       CHAR(1) DEFAULT '1', /* 1=Normal 2=Complementar 3=Ajuste 4=Devolução */
  TIPO_EMISSAO     CHAR(1) DEFAULT '1', /* 1=Normal 9=Contingência */
  AMBIENTE         CHAR(1) DEFAULT '2' CHECK (AMBIENTE IN ('1','2')), /* 1=Prod 2=Homolog */
  STATUS_NF        VARCHAR(20) DEFAULT 'DIGITACAO'
    CHECK (STATUS_NF IN ('DIGITACAO','VALIDADA','AUTORIZADA','CANCELADA','DENEGADA')),
  CHAVE_NF         VARCHAR(44),
  PROTOCOLO        VARCHAR(20),
  CNPJ_EMITENTE    VARCHAR(18),
  IE_EMITENTE      VARCHAR(20),
  RAZAO_EMITENTE   VARCHAR(100),
  /* Totais */
  VL_BC_ICMS       DM_VALOR,
  VL_ICMS          DM_VALOR,
  VL_BC_ICMS_ST    DM_VALOR,
  VL_ICMS_ST       DM_VALOR,
  VL_IPI           DM_VALOR,
  VL_PIS           DM_VALOR,
  VL_COFINS        DM_VALOR,
  VL_FRETE         DM_VALOR,
  VL_SEGURO        DM_VALOR,
  VL_DESCONTO      DM_VALOR,
  VL_OUTROS        DM_VALOR,
  VL_PRODUTOS      DM_VALOR,
  VL_TOTAL_NF      DM_VALOR,
  /* Transporte */
  MODALIDADE_FRETE CHAR(1) DEFAULT '9', /* 0=Emitente 1=Destinatário 9=SemFrete */
  /* Info adicionais */
  INFO_COMPL       VARCHAR(500),
  OBS_FISCO        VARCHAR(200),
  XML_NF           BLOB SUB_TYPE TEXT,
  DT_CADASTRO      DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_NF_SAIDA      PRIMARY KEY (ID),
  CONSTRAINT UQ_NF_NUM_SERIE  UNIQUE (NUMERO, SERIE),
  CONSTRAINT FK_NFS_CLIENTE   FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
  CONSTRAINT FK_NFS_VENDA     FOREIGN KEY (ID_VENDA)   REFERENCES VENDAS(ID),
  CONSTRAINT FK_NFS_USUARIO   FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE NF_SAIDA_ITENS (
  ID             DM_ID,
  ID_NF          INTEGER NOT NULL,
  ITEM           SMALLINT NOT NULL,
  ID_PRODUTO     INTEGER NOT NULL,
  CODIGO_PROD    VARCHAR(20),
  DESCRICAO      VARCHAR(120),
  NCM            VARCHAR(10),
  CFOP           VARCHAR(6),
  UNIDADE        VARCHAR(6),
  QUANTIDADE     DM_QTD NOT NULL,
  VL_UNITARIO    DM_VALOR NOT NULL,
  VL_DESCONTO    DM_VALOR,
  VL_FRETE       DM_VALOR,
  VL_SEGURO      DM_VALOR,
  VL_OUTROS      DM_VALOR,
  VL_PRODUTOS    DM_VALOR,
  /* ICMS */
  ORIG_PROD      CHAR(1) DEFAULT '0',
  CST_ICMS       VARCHAR(4),
  MODBC_ICMS     CHAR(1) DEFAULT '3',
  PRED_BC_ICMS   NUMERIC(7,2) DEFAULT 100,
  VL_BC_ICMS     DM_VALOR,
  ALIQ_ICMS      NUMERIC(7,2),
  VL_ICMS        DM_VALOR,
  /* PIS / COFINS */
  CST_PIS        VARCHAR(3),
  VL_BC_PIS      DM_VALOR,
  ALIQ_PIS       NUMERIC(7,4),
  VL_PIS         DM_VALOR,
  CST_COFINS     VARCHAR(3),
  VL_BC_COFINS   DM_VALOR,
  ALIQ_COFINS    NUMERIC(7,4),
  VL_COFINS      DM_VALOR,
  /* IPI */
  CST_IPI        VARCHAR(3),
  ALIQ_IPI       NUMERIC(7,2),
  VL_IPI         DM_VALOR,
  VL_TOTAL_ITEM  DM_VALOR,
  CONSTRAINT PK_NF_SAIDA_IT  PRIMARY KEY (ID),
  CONSTRAINT FK_NFSI_NF      FOREIGN KEY (ID_NF)      REFERENCES NF_SAIDA(ID) ON DELETE CASCADE,
  CONSTRAINT FK_NFSI_PROD    FOREIGN KEY (ID_PRODUTO)  REFERENCES PRODUTOS(ID)
);

SET TERM ^ ;
CREATE TRIGGER TBI_NF_SAIDA FOR NF_SAIDA ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_NF_SAIDA;
  IF (NEW.NUMERO IS NULL OR NEW.NUMERO = 0) THEN NEW.NUMERO = NEW.ID;
END^
CREATE TRIGGER TBI_NF_SAIDA_IT FOR NF_SAIDA_ITENS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_NF_SAIDA_ITENS; END^
SET TERM ; ^

/* ══════════════════════════════════════════════════════════
   CONTAS A PAGAR
   ══════════════════════════════════════════════════════════ */
CREATE TABLE CONTAS_PAGAR (
  ID              DM_ID,
  DESCRICAO       DM_NOME,
  ID_FORNECEDOR   INTEGER,
  ID_COMPRA       INTEGER,
  ID_FORMA_PGTO   INTEGER,
  ID_USUARIO      INTEGER NOT NULL,
  DT_EMISSAO      DM_DATA DEFAULT CURRENT_DATE,
  DT_VENCIMENTO   DM_DATA NOT NULL,
  DT_PAGAMENTO    DM_DATA,
  PARCELA         SMALLINT DEFAULT 1,
  TOTAL_PARCELAS  SMALLINT DEFAULT 1,
  VL_ORIGINAL     DM_VALOR NOT NULL,
  VL_JUROS        DM_VALOR,
  VL_MULTA        DM_VALOR,
  VL_DESCONTO     DM_VALOR,
  VL_PAGO         DM_VALOR,
  STATUS          VARCHAR(20) DEFAULT 'ABERTA'
    CHECK (STATUS IN ('ABERTA','PAGA','PAGA_PARCIAL','VENCIDA','CANCELADA')),
  NF_NUMERO       VARCHAR(20),
  HISTORICO       VARCHAR(200),
  OBS             VARCHAR(500),
  DT_CADASTRO     DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_CONTAS_PAGAR     PRIMARY KEY (ID),
  CONSTRAINT FK_CP_FORNECEDOR    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID),
  CONSTRAINT FK_CP_COMPRA        FOREIGN KEY (ID_COMPRA)     REFERENCES COMPRAS(ID),
  CONSTRAINT FK_CP_FORMA         FOREIGN KEY (ID_FORMA_PGTO) REFERENCES FORMAS_PGTO(ID),
  CONSTRAINT FK_CP_USUARIO       FOREIGN KEY (ID_USUARIO)    REFERENCES USUARIOS(ID)
);

CREATE TABLE PAGAMENTOS (
  ID             DM_ID,
  ID_CONTA       INTEGER NOT NULL,
  ID_FORMA_PGTO  INTEGER NOT NULL,
  ID_USUARIO     INTEGER NOT NULL,
  DT_PAGAMENTO   DM_DATA DEFAULT CURRENT_DATE,
  VL_PAGO        DM_VALOR NOT NULL,
  VL_JUROS       DM_VALOR,
  VL_MULTA       DM_VALOR,
  VL_DESCONTO    DM_VALOR,
  HISTORICO      VARCHAR(200),
  CONSTRAINT PK_PAGAMENTOS   PRIMARY KEY (ID),
  CONSTRAINT FK_PAG_CONTA    FOREIGN KEY (ID_CONTA)      REFERENCES CONTAS_PAGAR(ID),
  CONSTRAINT FK_PAG_FORMA    FOREIGN KEY (ID_FORMA_PGTO) REFERENCES FORMAS_PGTO(ID),
  CONSTRAINT FK_PAG_USUARIO  FOREIGN KEY (ID_USUARIO)    REFERENCES USUARIOS(ID)
);

/* ══════════════════════════════════════════════════════════
   CONTAS A RECEBER
   ══════════════════════════════════════════════════════════ */
CREATE TABLE CONTAS_RECEBER (
  ID              DM_ID,
  DESCRICAO       DM_NOME,
  ID_CLIENTE      INTEGER,
  ID_VENDA        INTEGER,
  ID_FORMA_PGTO   INTEGER,
  ID_USUARIO      INTEGER NOT NULL,
  DT_EMISSAO      DM_DATA DEFAULT CURRENT_DATE,
  DT_VENCIMENTO   DM_DATA NOT NULL,
  DT_RECEBIMENTO  DM_DATA,
  PARCELA         SMALLINT DEFAULT 1,
  TOTAL_PARCELAS  SMALLINT DEFAULT 1,
  VL_ORIGINAL     DM_VALOR NOT NULL,
  VL_JUROS        DM_VALOR,
  VL_MULTA        DM_VALOR,
  VL_DESCONTO     DM_VALOR,
  VL_RECEBIDO     DM_VALOR,
  STATUS          VARCHAR(20) DEFAULT 'ABERTA'
    CHECK (STATUS IN ('ABERTA','RECEBIDA','RECEBIDA_PARCIAL','VENCIDA','CANCELADA')),
  NF_NUMERO       VARCHAR(20),
  HISTORICO       VARCHAR(200),
  OBS             VARCHAR(500),
  DT_CADASTRO     DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_CONTAS_RECEBER   PRIMARY KEY (ID),
  CONSTRAINT FK_CR_CLIENTE       FOREIGN KEY (ID_CLIENTE)    REFERENCES CLIENTES(ID),
  CONSTRAINT FK_CR_VENDA         FOREIGN KEY (ID_VENDA)      REFERENCES VENDAS(ID),
  CONSTRAINT FK_CR_FORMA         FOREIGN KEY (ID_FORMA_PGTO) REFERENCES FORMAS_PGTO(ID),
  CONSTRAINT FK_CR_USUARIO       FOREIGN KEY (ID_USUARIO)    REFERENCES USUARIOS(ID)
);

CREATE TABLE RECEBIMENTOS (
  ID             DM_ID,
  ID_CONTA       INTEGER NOT NULL,
  ID_FORMA_PGTO  INTEGER NOT NULL,
  ID_USUARIO     INTEGER NOT NULL,
  DT_RECEBIMENTO DM_DATA  DEFAULT CURRENT_DATE,
  VL_RECEBIDO    DM_VALOR NOT NULL,
  VL_JUROS       DM_VALOR,
  VL_MULTA       DM_VALOR,
  VL_DESCONTO    DM_VALOR,
  HISTORICO      VARCHAR(200),
  CONSTRAINT PK_RECEBIMENTOS   PRIMARY KEY (ID),
  CONSTRAINT FK_REC_CONTA      FOREIGN KEY (ID_CONTA)      REFERENCES CONTAS_RECEBER(ID),
  CONSTRAINT FK_REC_FORMA      FOREIGN KEY (ID_FORMA_PGTO) REFERENCES FORMAS_PGTO(ID),
  CONSTRAINT FK_REC_USUARIO    FOREIGN KEY (ID_USUARIO)    REFERENCES USUARIOS(ID)
);

/* ══════════════════════════════════════════════════════════
   CAIXA / FLUXO DE CAIXA
   ══════════════════════════════════════════════════════════ */
CREATE TABLE CAIXAS (
  ID           DM_ID,
  DESCRICAO    DM_NOME,
  SALDO_ATUAL  DM_VALOR,
  ATIVO        DM_ATIVO,
  CONSTRAINT PK_CAIXAS PRIMARY KEY (ID)
);

CREATE TABLE CAIXA_MOV (
  ID             DM_ID,
  ID_CAIXA       INTEGER NOT NULL,
  ID_USUARIO     INTEGER NOT NULL,
  DT_MOV         DM_HORA DEFAULT CURRENT_TIMESTAMP,
  TIPO           CHAR(1) NOT NULL CHECK (TIPO IN ('E','S')), /* E=Entrada S=Saída */
  ORIGEM         VARCHAR(30),  /* PAGAMENTO/RECEBIMENTO/MANUAL/ABERTURA */
  ID_ORIGEM      INTEGER,
  DESCRICAO      VARCHAR(200) NOT NULL,
  VALOR          DM_VALOR NOT NULL,
  SALDO_ANTES    DM_VALOR,
  SALDO_DEPOIS   DM_VALOR,
  CONSTRAINT PK_CAIXA_MOV  PRIMARY KEY (ID),
  CONSTRAINT FK_CM_CAIXA   FOREIGN KEY (ID_CAIXA)   REFERENCES CAIXAS(ID),
  CONSTRAINT FK_CM_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

SET TERM ^ ;
CREATE TRIGGER TBI_CAIXAS FOR CAIXAS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_CAIXAS; END^
CREATE TRIGGER TBI_CAIXA_MOV FOR CAIXA_MOV ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_CAIXA_MOV; END^
CREATE TRIGGER TBI_PAGAMENTOS FOR PAGAMENTOS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_PAGAMENTOS; END^
CREATE TRIGGER TBI_RECEBIMENTOS FOR RECEBIMENTOS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_RECEBIMENTOS; END^
CREATE TRIGGER TBI_CONTAS_PAGAR FOR CONTAS_PAGAR ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_CONTAS_PAGAR; END^
CREATE TRIGGER TBI_CONTAS_RECEBER FOR CONTAS_RECEBER ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_CONTAS_RECEBER; END^

/* Atualiza saldo do caixa automaticamente ao inserir movimentação */
CREATE TRIGGER TAI_CAIXA_MOV FOR CAIXA_MOV ACTIVE AFTER INSERT POSITION 0
AS BEGIN
  IF (NEW.TIPO = 'E') THEN
    UPDATE CAIXAS SET SALDO_ATUAL = SALDO_ATUAL + NEW.VALOR WHERE ID = NEW.ID_CAIXA;
  ELSE
    UPDATE CAIXAS SET SALDO_ATUAL = SALDO_ATUAL - NEW.VALOR WHERE ID = NEW.ID_CAIXA;
END^

SET TERM ; ^

/* ── Views de Fluxo de Caixa ── */
CREATE VIEW VW_FLUXO_CAIXA AS
SELECT
  CM.ID, CM.DT_MOV, CM.TIPO, CM.DESCRICAO,
  CM.VALOR, CM.SALDO_DEPOIS, CM.ORIGEM,
  C.DESCRICAO AS CAIXA,
  U.NOME AS USUARIO
FROM CAIXA_MOV CM
JOIN CAIXAS C ON C.ID = CM.ID_CAIXA
JOIN USUARIOS U ON U.ID = CM.ID_USUARIO;

CREATE VIEW VW_CONTAS_VENCIDAS_PAGAR AS
SELECT CP.*,
  CURRENT_DATE - CP.DT_VENCIMENTO AS DIAS_ATRASO,
  F.NOME AS FORNECEDOR
FROM CONTAS_PAGAR CP
LEFT JOIN FORNECEDORES F ON F.ID = CP.ID_FORNECEDOR
WHERE CP.STATUS = 'ABERTA' AND CP.DT_VENCIMENTO < CURRENT_DATE;

CREATE VIEW VW_CONTAS_VENCIDAS_RECEBER AS
SELECT CR.*,
  CURRENT_DATE - CR.DT_VENCIMENTO AS DIAS_ATRASO,
  C.NOME AS CLIENTE
FROM CONTAS_RECEBER CR
LEFT JOIN CLIENTES C ON C.ID = CR.ID_CLIENTE
WHERE CR.STATUS = 'ABERTA' AND CR.DT_VENCIMENTO < CURRENT_DATE;

/* ── Dados iniciais ── */
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Dinheiro',         'DINHEIRO',         0);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('PIX',              'PIX',              0);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Cartão Débito',    'CARTAO_DEBITO',    1);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Cartão Crédito',   'CARTAO_CREDITO',  30);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Boleto 30 dias',   'BOLETO',          30);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Boleto 60 dias',   'BOLETO',          60);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Transferência',    'TRANSFERENCIA',    1);
INSERT INTO FORMAS_PGTO (DESCRICAO, TIPO, PRAZO_DIAS) VALUES ('Cheque à Vista',   'CHEQUE',           0);

INSERT INTO CAIXAS (DESCRICAO, SALDO_ATUAL) VALUES ('Caixa Principal', 0);

COMMIT;
