/*=============================================================
  LOGFACIL - Sistema ERP
  Banco: Firebird 3.0
  Criação completa do banco de dados
=============================================================*/

/* ── DOMÍNIOS ── */
CREATE DOMAIN DM_ID     AS INTEGER NOT NULL;
CREATE DOMAIN DM_NOME   AS VARCHAR(100) NOT NULL;
CREATE DOMAIN DM_DESC   AS VARCHAR(255);
CREATE DOMAIN DM_VALOR  AS NUMERIC(15,2) DEFAULT 0;
CREATE DOMAIN DM_QTD    AS NUMERIC(15,3) DEFAULT 0;
CREATE DOMAIN DM_ATIVO  AS CHAR(1) DEFAULT 'S' CHECK (VALUE IN ('S','N'));
CREATE DOMAIN DM_DATA   AS DATE;
CREATE DOMAIN DM_HORA   AS TIMESTAMP;
CREATE DOMAIN DM_SENHA  AS VARCHAR(64);
CREATE DOMAIN DM_PERFIL AS VARCHAR(20) CHECK (VALUE IN ('ADMINISTRADOR','GERENTE','OPERADOR'));
CREATE DOMAIN DM_TPMOV  AS CHAR(1) CHECK (VALUE IN ('E','S','A'));

/* ── SEQUENCES ── */
CREATE SEQUENCE SEQ_USUARIOS;
CREATE SEQUENCE SEQ_CLIENTES;
CREATE SEQUENCE SEQ_FORNECEDORES;
CREATE SEQUENCE SEQ_UNIDADES;
CREATE SEQUENCE SEQ_CATEGORIAS;
CREATE SEQUENCE SEQ_MAT_PRIMAS;
CREATE SEQUENCE SEQ_PRODUTOS;
CREATE SEQUENCE SEQ_COMPRAS;
CREATE SEQUENCE SEQ_COMP_ITENS;
CREATE SEQUENCE SEQ_VENDAS;
CREATE SEQUENCE SEQ_VEND_ITENS;
CREATE SEQUENCE SEQ_EST_MOV;
CREATE SEQUENCE SEQ_EST_MP_MOV;
CREATE SEQUENCE SEQ_AJUSTES;

/* ── TABELAS AUXILIARES ── */
CREATE TABLE UNIDADES (
  ID        DM_ID,
  SIGLA     VARCHAR(10) NOT NULL,
  DESCRICAO DM_NOME,
  ATIVO     DM_ATIVO,
  CONSTRAINT PK_UNIDADES   PRIMARY KEY (ID),
  CONSTRAINT UQ_UNID_SIGLA UNIQUE (SIGLA)
);

CREATE TABLE CATEGORIAS (
  ID        DM_ID,
  DESCRICAO DM_NOME,
  TIPO      CHAR(1) NOT NULL CHECK (TIPO IN ('P','M')), /* P=Produto M=MatPrima */
  ATIVO     DM_ATIVO,
  CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID)
);

/* ── USUÁRIOS ── */
CREATE TABLE USUARIOS (
  ID               DM_ID,
  NOME             DM_NOME,
  LOGIN            VARCHAR(50)  NOT NULL,
  SENHA            DM_SENHA     NOT NULL,
  EMAIL            VARCHAR(100),
  PERFIL           DM_PERFIL    DEFAULT 'OPERADOR',
  ATIVO            DM_ATIVO,
  DT_CADASTRO      DM_DATA      DEFAULT CURRENT_DATE,
  DT_ULTIMO_ACESSO DM_HORA,
  CONSTRAINT PK_USUARIOS  PRIMARY KEY (ID),
  CONSTRAINT UQ_USU_LOGIN UNIQUE (LOGIN)
);

/* ── CLIENTES ── */
CREATE TABLE CLIENTES (
  ID             DM_ID,
  TIPO_PESSOA    CHAR(1)      DEFAULT 'F' CHECK (TIPO_PESSOA IN ('F','J')),
  NOME           DM_NOME,
  NOME_FANTASIA  VARCHAR(100),
  CPF            VARCHAR(14),
  CNPJ           VARCHAR(18),
  RG             VARCHAR(20),
  IE             VARCHAR(20),
  EMAIL          VARCHAR(100),
  FONE1          VARCHAR(15),
  FONE2          VARCHAR(15),
  CEP            VARCHAR(9),
  LOGRADOURO     VARCHAR(150),
  NUMERO         VARCHAR(10),
  COMPLEMENTO    VARCHAR(50),
  BAIRRO         VARCHAR(80),
  CIDADE         VARCHAR(80),
  UF             CHAR(2),
  OBS            VARCHAR(500),
  LIMITE_CREDITO DM_VALOR,
  ATIVO          DM_ATIVO,
  DT_CADASTRO    DM_DATA DEFAULT CURRENT_DATE,
  CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
);

/* ── FORNECEDORES ── */
CREATE TABLE FORNECEDORES (
  ID            DM_ID,
  TIPO_PESSOA   CHAR(1)      DEFAULT 'J' CHECK (TIPO_PESSOA IN ('F','J')),
  NOME          DM_NOME,
  NOME_FANTASIA VARCHAR(100),
  CPF           VARCHAR(14),
  CNPJ          VARCHAR(18),
  IE            VARCHAR(20),
  EMAIL         VARCHAR(100),
  FONE1         VARCHAR(15),
  FONE2         VARCHAR(15),
  CEP           VARCHAR(9),
  LOGRADOURO    VARCHAR(150),
  NUMERO        VARCHAR(10),
  COMPLEMENTO   VARCHAR(50),
  BAIRRO        VARCHAR(80),
  CIDADE        VARCHAR(80),
  UF            CHAR(2),
  CONTATO       VARCHAR(80),
  OBS           VARCHAR(500),
  ATIVO         DM_ATIVO,
  DT_CADASTRO   DM_DATA DEFAULT CURRENT_DATE,
  CONSTRAINT PK_FORNECEDORES PRIMARY KEY (ID)
);

/* ── MATÉRIAS-PRIMAS ── */
CREATE TABLE MAT_PRIMAS (
  ID            DM_ID,
  CODIGO        VARCHAR(20) NOT NULL,
  DESCRICAO     DM_NOME,
  ID_CATEGORIA  INTEGER,
  ID_UNIDADE    INTEGER NOT NULL,
  CUSTO_MEDIO   DM_VALOR,
  ESTOQUE_ATUAL DM_QTD,
  ESTOQUE_MIN   DM_QTD,
  ESTOQUE_MAX   DM_QTD,
  LOCALIZACAO   VARCHAR(50),
  OBS           DM_DESC,
  ATIVO         DM_ATIVO,
  DT_CADASTRO   DM_DATA DEFAULT CURRENT_DATE,
  CONSTRAINT PK_MAT_PRIMAS   PRIMARY KEY (ID),
  CONSTRAINT UQ_MP_CODIGO    UNIQUE (CODIGO),
  CONSTRAINT FK_MP_CATEG     FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID),
  CONSTRAINT FK_MP_UNIDADE   FOREIGN KEY (ID_UNIDADE)   REFERENCES UNIDADES(ID)
);

/* ── PRODUTOS ── */
CREATE TABLE PRODUTOS (
  ID                 DM_ID,
  CODIGO             VARCHAR(20) NOT NULL,
  CODIGO_BARRAS      VARCHAR(30),
  DESCRICAO          DM_NOME,
  DESCRICAO_COMPLETA VARCHAR(500),
  ID_CATEGORIA       INTEGER,
  ID_UNIDADE         INTEGER NOT NULL,
  PRECO_CUSTO        DM_VALOR,
  PRECO_VENDA        DM_VALOR NOT NULL,
  MARGEM_LUCRO       NUMERIC(7,2),
  ESTOQUE_ATUAL      DM_QTD,
  ESTOQUE_MIN        DM_QTD,
  ESTOQUE_MAX        DM_QTD,
  NCM                VARCHAR(10),
  CFOP               VARCHAR(6),
  OBS                DM_DESC,
  ATIVO              DM_ATIVO,
  DT_CADASTRO        DM_DATA DEFAULT CURRENT_DATE,
  CONSTRAINT PK_PRODUTOS    PRIMARY KEY (ID),
  CONSTRAINT UQ_PROD_CODIGO UNIQUE (CODIGO),
  CONSTRAINT FK_PROD_CATEG  FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID),
  CONSTRAINT FK_PROD_UNID   FOREIGN KEY (ID_UNIDADE)   REFERENCES UNIDADES(ID)
);

/* ── COMPRAS DE MATÉRIA-PRIMA ── */
CREATE TABLE COMPRAS (
  ID             DM_ID,
  NUMERO         INTEGER NOT NULL,
  ID_FORNECEDOR  INTEGER NOT NULL,
  ID_USUARIO     INTEGER NOT NULL,
  DT_EMISSAO     DM_DATA DEFAULT CURRENT_DATE,
  DT_PREVISAO    DM_DATA,
  DT_RECEBIMENTO DM_DATA,
  STATUS         VARCHAR(20) DEFAULT 'PENDENTE'
    CHECK (STATUS IN ('PENDENTE','CONFIRMADA','RECEBIDA','CANCELADA')),
  NF_NUMERO      VARCHAR(20),
  NF_SERIE       VARCHAR(5),
  VL_PRODUTOS    DM_VALOR,
  VL_FRETE       DM_VALOR,
  VL_DESCONTO    DM_VALOR,
  VL_TOTAL       DM_VALOR,
  COND_PAGTO     VARCHAR(60),
  OBS            VARCHAR(500),
  DT_CADASTRO    DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_COMPRAS        PRIMARY KEY (ID),
  CONSTRAINT UQ_COMP_NUM       UNIQUE (NUMERO),
  CONSTRAINT FK_COMP_FORNEC    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID),
  CONSTRAINT FK_COMP_USUARIO   FOREIGN KEY (ID_USUARIO)    REFERENCES USUARIOS(ID)
);

CREATE TABLE COMPRAS_ITENS (
  ID           DM_ID,
  ID_COMPRA    INTEGER NOT NULL,
  ITEM         SMALLINT NOT NULL,
  ID_MAT_PRIMA INTEGER NOT NULL,
  QUANTIDADE   DM_QTD  NOT NULL,
  VL_UNITARIO  DM_VALOR NOT NULL,
  VL_DESCONTO  DM_VALOR,
  VL_TOTAL     DM_VALOR NOT NULL,
  CONSTRAINT PK_COMP_ITENS  PRIMARY KEY (ID),
  CONSTRAINT FK_CI_COMPRA   FOREIGN KEY (ID_COMPRA)    REFERENCES COMPRAS(ID)     ON DELETE CASCADE,
  CONSTRAINT FK_CI_MP       FOREIGN KEY (ID_MAT_PRIMA) REFERENCES MAT_PRIMAS(ID)
);

/* ── VENDAS DE PRODUTOS ── */
CREATE TABLE VENDAS (
  ID             DM_ID,
  NUMERO         INTEGER NOT NULL,
  ID_CLIENTE     INTEGER NOT NULL,
  ID_USUARIO     INTEGER NOT NULL,
  DT_EMISSAO     DM_DATA DEFAULT CURRENT_DATE,
  DT_ENTREGA     DM_DATA,
  DT_FATURAMENTO DM_DATA,
  STATUS         VARCHAR(20) DEFAULT 'ORCAMENTO'
    CHECK (STATUS IN ('ORCAMENTO','CONFIRMADA','FATURADA','ENTREGUE','CANCELADA')),
  NF_NUMERO      VARCHAR(20),
  NF_SERIE       VARCHAR(5),
  VL_PRODUTOS    DM_VALOR,
  VL_FRETE       DM_VALOR,
  VL_DESCONTO    DM_VALOR,
  VL_TOTAL       DM_VALOR,
  COND_PAGTO     VARCHAR(60),
  OBS            VARCHAR(500),
  DT_CADASTRO    DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_VENDAS      PRIMARY KEY (ID),
  CONSTRAINT UQ_VEND_NUM    UNIQUE (NUMERO),
  CONSTRAINT FK_VND_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
  CONSTRAINT FK_VND_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE VENDAS_ITENS (
  ID          DM_ID,
  ID_VENDA    INTEGER NOT NULL,
  ITEM        SMALLINT NOT NULL,
  ID_PRODUTO  INTEGER NOT NULL,
  QUANTIDADE  DM_QTD  NOT NULL,
  VL_UNITARIO DM_VALOR NOT NULL,
  VL_DESCONTO DM_VALOR,
  VL_TOTAL    DM_VALOR NOT NULL,
  CONSTRAINT PK_VEND_ITENS PRIMARY KEY (ID),
  CONSTRAINT FK_VI_VENDA   FOREIGN KEY (ID_VENDA)   REFERENCES VENDAS(ID)    ON DELETE CASCADE,
  CONSTRAINT FK_VI_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);

/* ── MOVIMENTAÇÃO DE ESTOQUE – PRODUTOS ── */
CREATE TABLE ESTOQUE_MOV (
  ID           DM_ID,
  ID_PRODUTO   INTEGER NOT NULL,
  ID_USUARIO   INTEGER NOT NULL,
  DT_MOV       DM_HORA DEFAULT CURRENT_TIMESTAMP,
  TIPO_MOV     DM_TPMOV NOT NULL,   /* E=Entrada S=Saída A=Ajuste */
  ORIGEM       VARCHAR(20),         /* COMPRA/VENDA/AJUSTE/INVENTARIO */
  ID_ORIGEM    INTEGER,
  QUANTIDADE   DM_QTD NOT NULL,
  VL_UNITARIO  DM_VALOR,
  VL_TOTAL     DM_VALOR,
  EST_ANTES    DM_QTD,
  EST_DEPOIS   DM_QTD,
  OBS          DM_DESC,
  CONSTRAINT PK_EST_MOV  PRIMARY KEY (ID),
  CONSTRAINT FK_EM_PROD  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID),
  CONSTRAINT FK_EM_USU   FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

/* ── MOVIMENTAÇÃO DE ESTOQUE – MAT. PRIMAS ── */
CREATE TABLE ESTOQUE_MP_MOV (
  ID           DM_ID,
  ID_MAT_PRIMA INTEGER NOT NULL,
  ID_USUARIO   INTEGER NOT NULL,
  DT_MOV       DM_HORA DEFAULT CURRENT_TIMESTAMP,
  TIPO_MOV     DM_TPMOV NOT NULL,
  ORIGEM       VARCHAR(20),
  ID_ORIGEM    INTEGER,
  QUANTIDADE   DM_QTD NOT NULL,
  VL_UNITARIO  DM_VALOR,
  VL_TOTAL     DM_VALOR,
  EST_ANTES    DM_QTD,
  EST_DEPOIS   DM_QTD,
  OBS          DM_DESC,
  CONSTRAINT PK_EST_MP_MOV PRIMARY KEY (ID),
  CONSTRAINT FK_EMMP_MP    FOREIGN KEY (ID_MAT_PRIMA) REFERENCES MAT_PRIMAS(ID),
  CONSTRAINT FK_EMMP_USU   FOREIGN KEY (ID_USUARIO)   REFERENCES USUARIOS(ID)
);

/* ── AJUSTES MANUAIS DE ESTOQUE ── */
CREATE TABLE AJUSTES_ESTOQUE (
  ID          DM_ID,
  NUMERO      INTEGER NOT NULL,
  ID_USUARIO  INTEGER NOT NULL,
  DT_AJUSTE   DM_DATA DEFAULT CURRENT_DATE,
  TIPO_EST    CHAR(1) NOT NULL CHECK (TIPO_EST IN ('P','M')),
  MOTIVO      VARCHAR(100) NOT NULL,
  OBS         VARCHAR(500),
  DT_CADASTRO DM_HORA DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AJUSTES    PRIMARY KEY (ID),
  CONSTRAINT UQ_AJ_NUM     UNIQUE (NUMERO),
  CONSTRAINT FK_AJ_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE AJUSTES_ITENS (
  ID           DM_ID,
  ID_AJUSTE    INTEGER  NOT NULL,
  ITEM         SMALLINT NOT NULL,
  TIPO_EST     CHAR(1)  NOT NULL CHECK (TIPO_EST IN ('P','M')),
  ID_PRODUTO   INTEGER,
  ID_MAT_PRIMA INTEGER,
  DESCRICAO    VARCHAR(100),
  TIPO_MOV     DM_TPMOV NOT NULL,
  QTD_ANTERIOR DM_QTD,
  QTD_NOVA     DM_QTD,
  DIFERENCA    DM_QTD,
  VL_UNITARIO  DM_VALOR,
  OBS          DM_DESC,
  CONSTRAINT PK_AJ_ITENS   PRIMARY KEY (ID),
  CONSTRAINT FK_AJI_AJUSTE FOREIGN KEY (ID_AJUSTE)    REFERENCES AJUSTES_ESTOQUE(ID) ON DELETE CASCADE,
  CONSTRAINT FK_AJI_PROD   FOREIGN KEY (ID_PRODUTO)   REFERENCES PRODUTOS(ID),
  CONSTRAINT FK_AJI_MP     FOREIGN KEY (ID_MAT_PRIMA) REFERENCES MAT_PRIMAS(ID)
);

/* ══════════════════════════════════
   TRIGGERS – AUTO INCREMENT
   ══════════════════════════════════ */
SET TERM ^ ;

CREATE TRIGGER TBI_UNIDADES FOR UNIDADES ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_UNIDADES; END^

CREATE TRIGGER TBI_CATEGORIAS FOR CATEGORIAS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_CATEGORIAS; END^

CREATE TRIGGER TBI_USUARIOS FOR USUARIOS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_USUARIOS; END^

CREATE TRIGGER TBI_CLIENTES FOR CLIENTES ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_CLIENTES; END^

CREATE TRIGGER TBI_FORNECEDORES FOR FORNECEDORES ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_FORNECEDORES; END^

CREATE TRIGGER TBI_MAT_PRIMAS FOR MAT_PRIMAS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_MAT_PRIMAS; END^

CREATE TRIGGER TBI_PRODUTOS FOR PRODUTOS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_PRODUTOS; END^

CREATE TRIGGER TBI_COMPRAS FOR COMPRAS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_COMPRAS;
  IF (NEW.NUMERO IS NULL OR NEW.NUMERO = 0) THEN NEW.NUMERO = NEW.ID;
END^

CREATE TRIGGER TBI_COMP_ITENS FOR COMPRAS_ITENS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_COMP_ITENS; END^

CREATE TRIGGER TBI_VENDAS FOR VENDAS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_VENDAS;
  IF (NEW.NUMERO IS NULL OR NEW.NUMERO = 0) THEN NEW.NUMERO = NEW.ID;
END^

CREATE TRIGGER TBI_VEND_ITENS FOR VENDAS_ITENS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_VEND_ITENS; END^

CREATE TRIGGER TBI_EST_MOV FOR ESTOQUE_MOV ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_EST_MOV; END^

CREATE TRIGGER TBI_EST_MP_MOV FOR ESTOQUE_MP_MOV ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_EST_MP_MOV; END^

CREATE TRIGGER TBI_AJUSTES FOR AJUSTES_ESTOQUE ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_AJUSTES;
  IF (NEW.NUMERO IS NULL OR NEW.NUMERO = 0) THEN NEW.NUMERO = NEW.ID;
END^

CREATE TRIGGER TBI_AJUSTES_ITENS FOR AJUSTES_ITENS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = NEXT VALUE FOR SEQ_AJUSTES; END^

/* ══════════════════════════════════
   TRIGGER – RECEBIMENTO DE COMPRA
   Atualiza estoque MP + custo médio
   ══════════════════════════════════ */
CREATE TRIGGER TAU_COMPRA_RECEBER FOR COMPRAS
  ACTIVE AFTER UPDATE POSITION 0
AS
  DECLARE VARIABLE VID_MP   INTEGER;
  DECLARE VARIABLE VQTD     NUMERIC(15,3);
  DECLARE VARIABLE VVLU     NUMERIC(15,2);
  DECLARE VARIABLE VEST_ANT NUMERIC(15,3);
  DECLARE VARIABLE VCMED    NUMERIC(15,2);
BEGIN
  IF (NEW.STATUS = 'RECEBIDA' AND OLD.STATUS <> 'RECEBIDA') THEN
  BEGIN
    FOR SELECT CI.ID_MAT_PRIMA, CI.QUANTIDADE, CI.VL_UNITARIO
        FROM COMPRAS_ITENS CI WHERE CI.ID_COMPRA = NEW.ID
        INTO :VID_MP, :VQTD, :VVLU
    DO BEGIN
      SELECT ESTOQUE_ATUAL, CUSTO_MEDIO FROM MAT_PRIMAS
        WHERE ID = :VID_MP INTO :VEST_ANT, :VCMED;

      IF ((:VEST_ANT + :VQTD) > 0) THEN
        VCMED = ((:VEST_ANT * :VCMED) + (:VQTD * :VVLU)) / (:VEST_ANT + :VQTD);

      UPDATE MAT_PRIMAS
        SET ESTOQUE_ATUAL = ESTOQUE_ATUAL + :VQTD,
            CUSTO_MEDIO   = :VCMED
        WHERE ID = :VID_MP;

      INSERT INTO ESTOQUE_MP_MOV
        (ID_MAT_PRIMA,ID_USUARIO,TIPO_MOV,ORIGEM,ID_ORIGEM,
         QUANTIDADE,VL_UNITARIO,VL_TOTAL,EST_ANTES,EST_DEPOIS)
      VALUES
        (:VID_MP,NEW.ID_USUARIO,'E','COMPRA',NEW.ID,
         :VQTD,:VVLU,:VQTD*:VVLU,:VEST_ANT,:VEST_ANT+:VQTD);
    END
    UPDATE COMPRAS SET DT_RECEBIMENTO = CURRENT_DATE WHERE ID = NEW.ID;
  END
END^

/* ══════════════════════════════════
   TRIGGER – FATURAMENTO DE VENDA
   Debita estoque de produtos
   ══════════════════════════════════ */
CREATE TRIGGER TAU_VENDA_FATURAR FOR VENDAS
  ACTIVE AFTER UPDATE POSITION 0
AS
  DECLARE VARIABLE VID_PROD INTEGER;
  DECLARE VARIABLE VQTD     NUMERIC(15,3);
  DECLARE VARIABLE VVLU     NUMERIC(15,2);
  DECLARE VARIABLE VEST_ANT NUMERIC(15,3);
BEGIN
  /* Faturamento: debita estoque */
  IF (NEW.STATUS = 'FATURADA' AND OLD.STATUS <> 'FATURADA') THEN
  BEGIN
    FOR SELECT VI.ID_PRODUTO, VI.QUANTIDADE, VI.VL_UNITARIO
        FROM VENDAS_ITENS VI WHERE VI.ID_VENDA = NEW.ID
        INTO :VID_PROD, :VQTD, :VVLU
    DO BEGIN
      SELECT ESTOQUE_ATUAL FROM PRODUTOS
        WHERE ID = :VID_PROD INTO :VEST_ANT;

      UPDATE PRODUTOS SET ESTOQUE_ATUAL = ESTOQUE_ATUAL - :VQTD WHERE ID = :VID_PROD;

      INSERT INTO ESTOQUE_MOV
        (ID_PRODUTO,ID_USUARIO,TIPO_MOV,ORIGEM,ID_ORIGEM,
         QUANTIDADE,VL_UNITARIO,VL_TOTAL,EST_ANTES,EST_DEPOIS)
      VALUES
        (:VID_PROD,NEW.ID_USUARIO,'S','VENDA',NEW.ID,
         :VQTD,:VVLU,:VQTD*:VVLU,:VEST_ANT,:VEST_ANT-:VQTD);
    END
    UPDATE VENDAS SET DT_FATURAMENTO = CURRENT_DATE WHERE ID = NEW.ID;
  END

  /* Cancelamento de venda faturada: estorno automático */
  IF (NEW.STATUS = 'CANCELADA' AND OLD.STATUS = 'FATURADA') THEN
  BEGIN
    FOR SELECT VI.ID_PRODUTO, VI.QUANTIDADE, VI.VL_UNITARIO
        FROM VENDAS_ITENS VI WHERE VI.ID_VENDA = NEW.ID
        INTO :VID_PROD, :VQTD, :VVLU
    DO BEGIN
      SELECT ESTOQUE_ATUAL FROM PRODUTOS
        WHERE ID = :VID_PROD INTO :VEST_ANT;

      UPDATE PRODUTOS SET ESTOQUE_ATUAL = ESTOQUE_ATUAL + :VQTD WHERE ID = :VID_PROD;

      INSERT INTO ESTOQUE_MOV
        (ID_PRODUTO,ID_USUARIO,TIPO_MOV,ORIGEM,ID_ORIGEM,
         QUANTIDADE,VL_UNITARIO,VL_TOTAL,EST_ANTES,EST_DEPOIS,OBS)
      VALUES
        (:VID_PROD,NEW.ID_USUARIO,'E','CANCELAMENTO',NEW.ID,
         :VQTD,:VVLU,:VQTD*:VVLU,:VEST_ANT,:VEST_ANT+:VQTD,
         'Estorno - Cancelamento Venda ' || NEW.NUMERO);
    END
  END
END^

SET TERM ; ^

/* ── VIEWS DE POSIÇÃO DE ESTOQUE ── */
CREATE VIEW VW_POSICAO_PRODUTOS AS
SELECT P.ID, P.CODIGO, P.DESCRICAO,
       U.SIGLA AS UNIDADE,
       P.ESTOQUE_ATUAL, P.ESTOQUE_MIN, P.ESTOQUE_MAX,
       P.PRECO_CUSTO, P.PRECO_VENDA,
       P.ESTOQUE_ATUAL * P.PRECO_CUSTO AS VL_CUSTO_TOTAL,
       CASE
         WHEN P.ESTOQUE_ATUAL <= 0                                   THEN 'SEM ESTOQUE'
         WHEN P.ESTOQUE_ATUAL < P.ESTOQUE_MIN                        THEN 'ESTOQUE BAIXO'
         WHEN P.ESTOQUE_MAX > 0 AND P.ESTOQUE_ATUAL > P.ESTOQUE_MAX  THEN 'ESTOQUE ALTO'
         ELSE 'NORMAL'
       END AS SITUACAO
FROM PRODUTOS P
LEFT JOIN UNIDADES U ON U.ID = P.ID_UNIDADE
WHERE P.ATIVO = 'S';

CREATE VIEW VW_POSICAO_MP AS
SELECT MP.ID, MP.CODIGO, MP.DESCRICAO,
       U.SIGLA AS UNIDADE,
       MP.ESTOQUE_ATUAL, MP.ESTOQUE_MIN, MP.ESTOQUE_MAX,
       MP.CUSTO_MEDIO,
       MP.ESTOQUE_ATUAL * MP.CUSTO_MEDIO AS VL_TOTAL,
       CASE
         WHEN MP.ESTOQUE_ATUAL <= 0                                    THEN 'SEM ESTOQUE'
         WHEN MP.ESTOQUE_ATUAL < MP.ESTOQUE_MIN                        THEN 'ESTOQUE BAIXO'
         WHEN MP.ESTOQUE_MAX > 0 AND MP.ESTOQUE_ATUAL > MP.ESTOQUE_MAX THEN 'ESTOQUE ALTO'
         ELSE 'NORMAL'
       END AS SITUACAO
FROM MAT_PRIMAS MP
LEFT JOIN UNIDADES U ON U.ID = MP.ID_UNIDADE
WHERE MP.ATIVO = 'S';

/* ── DADOS INICIAIS ── */
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('UN',  'Unidade');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('KG',  'Quilograma');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('G',   'Grama');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('L',   'Litro');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('ML',  'Mililitro');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('M',   'Metro');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('M2',  'Metro Quadrado');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('CX',  'Caixa');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('PCT', 'Pacote');
INSERT INTO UNIDADES (SIGLA, DESCRICAO) VALUES ('PC',  'Peça');

INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Eletrônicos',  'P');
INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Mecânicos',    'P');
INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Consumíveis',  'P');
INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Metais',       'M');
INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Plásticos',    'M');
INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Químicos',     'M');
INSERT INTO CATEGORIAS (DESCRICAO, TIPO) VALUES ('Embalagens',   'M');

/* Usuário padrão: login=admin  senha=admin123 (SHA-256) */
INSERT INTO USUARIOS (NOME, LOGIN, SENHA, PERFIL, EMAIL)
VALUES ('Administrador', 'admin',
        '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
        'ADMINISTRADOR', 'admin@logfacil.com.br');

COMMIT;
